---
title: "analysis peak"
author: "ajpelu"
date: "2023-06-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(janitor) 
library(lubridate)
library(ggpubr)
library(Kendall)
library(trend)
```


```{r}
df_doy <- read_csv(here::here("data/doy_peak_sps.csv"))
transectos <- read_csv(here::here("data/transectos_metadata.csv"))
```


```{r}
plot_trend_doy_all <- function(df, sp){ 
  p <- df |> 
    filter(species == sp) |> 
    mutate(abb = fct_reorder(abb_elev, altitud)) |> 
    ggplot(aes(x=year, y=doy)) + 
    geom_point() + 
    facet_wrap(~abb) +
    geom_smooth(method = "lm", se = FALSE) +
    ggpubr::stat_cor(
      aes(label = after_stat(rr.label))
      ) + 
    theme_bw() +
    theme(
    panel.grid= element_blank(), 
    strip.background = element_blank()) + 
    ylab("Day of year") + xlab("Year") + 
  labs(
    title = sp
  )  +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 2)) 
  
  return(p)
  }

```

```{r}
# Get species 
species <- unique(df_doy$species)

# Generate PDF files for each species using purrr::map()
map(species, ~{
  sp <- .
  p <- plot_trend_doy(df_doy, sp)
  pdf_file <- here::here("output/pheno_peak_doy/", paste0(sp, ".pdf"))
  ggsave(filename = pdf_file, plot = p, device = "pdf")
})
```


```{r}

plot_trend_doy_all_points <- function(df, sp, min_points){ 
  p <- df |> 
    ungroup() |> 
    filter(species == sp) |> 
    mutate(abb = fct_reorder(abb_elev, altitud)) |> 
    group_by(abb) |> 
    mutate(num_points = n()) |> 
    filter(num_points > min_points) |> 
    ggplot(aes(x=year, y=doy)) + 
    geom_point() + 
    facet_wrap(~abb) +
    geom_smooth(method = "lm", se = FALSE) +
    ggpubr::stat_cor(
      aes(label = after_stat(rr.label))
      ) + 
    theme_bw() +
    theme(
    panel.grid= element_blank(), 
    strip.background = element_blank()) + 
    ylab("Day of year") + xlab("Year") + 
  labs(
    title = sp
  )  +
    scale_x_continuous(breaks = seq(min(df$year), max(df$year), by = 2)) 
  
  return(p)
}

plot_trend_doy_all_points(df_doy, sp = "Aglais urticae", min_points = 4)

```

```{r, eval=FALSE}
### error, falla cuando no hay min points 
map(species, ~{
  sp <- .
  p <- plot_trend_doy_all_points(df_doy, sp, min_points = 4)
  pdf_file <- here::here("output/pheno_peak_doy5/", paste0(sp, ".pdf"))
  ggsave(filename = pdf_file, plot = p, device = "pdf")
})
```

Compute the number of sites where the sps are present and the number of sites with more than 4 points 

```{r}
npoints_sp_site <- df_doy |> 
    ungroup() |> 
    group_by(species, site_id, abb_elev) |> 
  summarise(num_points = n())

nsites_by_sps <- npoints_sp_site |> 
  group_by(species) |> 
  summarise(nsites = n())

nsites_by_sps_4points <- npoints_sp_site |>
  filter(num_points > 4) |> 
  group_by(species) |> 
  summarise(nsites_higher4points = n())


ns <- nsites_by_sps |> 
  full_join(nsites_by_sps_4points)
```




# Compute trend 

```{r}
compute_trend <- function(y, x) {
  # Compute Mann-Kendall test
  mk <- MannKendall(y)
  mk_tau <- mk$tau
  mk_pvalue <- mk$sl
  
  # Compute Sen's slope
  sen <- trend::sens.slope(y)
  sen_slope <- unname(sen$estimates)
  sen_stats <- unname(sen$statistic)
  sen_pvalue <- unname(sen$p.value)

  # Compute LM 
  model <- lm(y ~ x)
  lm_slope <- model$coefficients[2]
  lm_pvalue <- summary(model)$coefficients[2,4]
  lm_rsquared <- summary(model)$r.squared


  # Check for NULL values
  if (is.null(mk_tau)) mk_tau <- NA
  if (is.null(mk_pvalue)) mk_pvalue <- NA
  if (is.null(sen_slope)) sen_slope <- NA
  if (is.null(sen_stats)) sen_stats <- NA
  if (is.null(sen_pvalue)) sen_pvalue <- NA
  if (is.null(lm_slope)) lm_slope <- NA
  if (is.null(lm_pvalue)) lm_pvalue <- NA
  if (is.null(lm_rsquared)) lm_rsquared <- NA

  
  # Return results
  result <- data.frame(mk_tau = mk_tau, 
                       mk_pvalue = mk_pvalue, 
                       sen_slope = sen_slope, 
                       sen_stats = sen_stats, 
                       sen_pvalue = sen_pvalue, 
                       lm_slope = lm_slope, 
                       lm_pvalue = lm_pvalue, 
                       lm_rsquared = lm_rsquared)

  return(result)
}



df_trends <- df_doy |> 
  ungroup() |> 
  group_by(species, site_id) |> 
  mutate(num_points = n()) |> 
  filter(num_points > 4)  |> 
  group_modify(~compute_trend(.x$doy, .x$year)) |> 
  inner_join(transectos)

```


```{r}
df_trends |> 
  ggplot(aes(x=altitud, y = sen_slope)) + geom_point() +
  theme_bw()
```






```{r}
  unite("abb", c("altitud","abreviatura"), remove = FALSE) |>
  mutate(abb = fct_reorder(abb, altitud)) |> 
  ggplot(aes(x=doy, y=nm, colour = as.factor(year))) + 
  geom_point() + 
  geom_path() + 
  facet_wrap(~abb) + 
  theme_bw() + 
  theme(
    panel.grid= element_blank(), 
    strip.background = element_blank()
  ) + ylab("") +
  labs(
    title = "Aglais urticae",
    colour = "Year"
  )






df_doy |> 
  filter(species == "Aglais urticae") |> 
  mutate(abb = fct_reorder(abb_elev, altitud)) |> 
  ggplot(aes(x=year, y=doy)) + 
  geom_point() + 
  facet_wrap(~abb) +
  geom_smooth(method = "lm", se = FALSE) +
  ggpubr::stat_cor(
    aes(label = after_stat(rr.label))  
  ) + theme_bw()

```


```{r}

df_doy  |> 
  filter(species == "Aglais urticae") |> 
  unite("abb", c("altitud","abreviatura"), remove = FALSE) |>
  mutate(abb = fct_reorder(abreviatura, altitud)) |> 
  ggplot(aes(x=year, y=doy)) + 
  geom_point() + 
  facet_wrap(~abb_elev) +
  geom_smooth(method = "lm", se = FALSE) +
  ggpubr::stat_cor(
    aes(label = after_stat(rr.label))  
  ) +
  theme_bw()

```








```{r}


d |> 
  unite("abb", c("altitud","abreviatura"), remove = FALSE) |>
  mutate(abb = fct_reorder(abb, altitud)) |> 
  ggplot(aes(x=doy, y=nm, colour = as.factor(year))) + 
  geom_point() + 
  geom_path() + 
  facet_wrap(~abb) + 
  theme_bw() + 
  theme(
    panel.grid= element_blank(), 
    strip.background = element_blank()
  ) + ylab("") +
  labs(
    title = "Aglais urticae",
    colour = "Year"
  )

```



```{r}
sps <- unique(pheno$species)
```


Generate for each species, site and year, the day with the maximum peak of the fitted abundance 


```{r}



peak_day %>%
  inner_join(transectos) %>%
  filter(species == "Aglais urticae") %>%
  unite("abb", c("altitud", "abreviatura"), remove = FALSE) %>%
  mutate(abb = fct_reorder(abreviatura, altitud)) %>%
  group_by(abb) %>%
  mutate(num_points = n()) %>%
  filter(num_points > 4) %>%
  ggplot(aes(x = year, y = doy)) +
  geom_point() +
  facet_wrap(~ abb) +
  geom_smooth(method = "lm", se = FALSE) +
  ggpubr::stat_cor(
    aes(label = after_stat(rr.label))
  ) +
  theme_bw()









```


```{r}
library(ggplot2)
library(dplyr)
library(forcats)

peak_day %>%
  inner_join(transectos) %>%
  filter(species == "Aglais urticae") %>%
  unite("abb", c("altitud","abreviatura"), remove = FALSE) %>%
  mutate(abb = fct_reorder(abb, altitud)) %>%
  ggplot(aes(x = year, y = doy)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(
    ~ abb,
    labeller = labeller(
      abb = function(variable) {
        r_squared <- summary(lm(doy ~ year, data = subset(., abb == variable)))$adj.r.squared
        p_value <- summary(lm(doy ~ year, data = subset(., abb == variable)))$coefficients[8, 4]
        label <- paste(variable, "R-squared:", round(r_squared, 2), "p-value:", round(p_value, 2))
        label
      }
    )
  )

```


```{r}
# pheno <- readxl::read_excel("data/raw_data/pheno.xlsx") |>
#   janitor::clean_names() |> 
#   mutate(date = lubridate::make_date(year, month, day)) |>
#   mutate(doy = lubridate::yday(date)) |> 
#   inner_join(transectos)
```

