---
title: "Prepare Transects data"
author: "ajpelu"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

- Prepare transect data for use it thorough the analysis

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(here)
```


```{r}

# Prepare variable transects
transectos <- readxl::read_excel("data/raw_data/Tabla_variables_transectos_22.xls", 
                                 sheet = "Otras variables") |>
  janitor::clean_names() |> 
  filter(transecto != "ENSNEVADA")

write_csv(transectos, "data/transectos_variables.csv")


# Read the transect data 
transectos_metadata <- transectos |> 
  dplyr::select(transecto, id_transect, abreviatura, altitud) |> 
  mutate(site_id = as.numeric(gsub("16_", "", id_transect))) |> 
  unite("abb_elev", c("abreviatura", "altitud"), sep = " (", remove = FALSE) |> 
  mutate(abb_elev = paste0(abb_elev, ")"))

write_csv(transectos_metadata, here::here("data/transectos_metadata.csv"))
```

